name: "Docs check and push"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Push docs check"
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    - uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: docs/build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html